quarkusio/extensions

gatsby-config.js
Most internal links on the page were broken by the links broken by rename and transfer of the git repo.
=> Update path and site URL to resolve dead links

src/components/filters/filters.js, src/components/filters/filters.test.js
Given the number of extensions is relatively small, I don't think we run too much risk of false positives if we include the description. It means, for example, if someone searches for "soap" they would find 'cxf', which is probably what they'd expect.
=> Include description in what we search

.github/workflows/build_and_publish.yml, test-integration/frontpage.test.js, test-integration/links.test.js
Resolves https://github.com/quarkusio/extensions.quarkus.io/issues/1 by running integration tests in their own stage, before attempting a deploy.
Resolves https://github.com/quarkusio/extensions.quarkus.io/issues/7 by adding an extra wait with `{hidden: true}`. I suspect the extension is a bit slower to disappear out of the dom in the servers. I don't totally trust the {hidden: true} so I've left in the original check as well.
Also (sigh) adds some exclusions for known dead links that have been waiting for releases for a couple of months.
Also updates it so that we test (but do not deploy, obvs) from PRs.
=>  Fix integration tests, and build forks

gatsby-node.js, gatsby-node.test.js, src/components/extension-card.js, src/components/extension-card.test.js, src/components/filters/filters.js, src/components/filters/filters.test.js, src/pages/index.js, src/templates/extension-detail-page.test.js, src/templates/extension-detail.js
Resolves #15.
See discussion at https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Listing.20unlisted.20extensions/near/310598347
=> Hide unlisted extensions unless explicitly searched for

test-integration/frontpage.test.js, test-integration/links.test.js
The changes in #15 broke the integration tests, because we look for ArC but ArC is an unlisted extension. 
The `security-jpa` extension's guide link was fixed in 2.14.2 Quarkus release, but we list the 3.0.0.Alpha extension, which still has the problematic link, so we need to add an exclusion.
=> Test fixes

README.md
Although `gatsby` can be handy to save typing, it's not needed in any way, so simplify setup instructions.
=> Make it more clear that no gatsby install is needed in setup instructions

gatsby-config.js, package-lock.json, package.json, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/package.json, src/components/extension-card.js, src/components/extension-card.test.js, src/pages/index.js
Now that some extensions in the registry have their source control coordinates, we can use that information to fill in a picture.
This is partial resolution of #23, although more work is needed. Support for overrides will be needed, especially for extensions in the main quarkus repository, which will all look the same.
=> Where available, use the GitHub organisation avatar as the logo

gatsby-config.js
I'm seeing errors in the logs (bad) and inconsistent data in the UI (terrible), because of the remote images plugin not tolerating missing images. I've raised https://github.com/graysonhicks/gatsby-plugin-remote-images/issues/120, but as a workaround, I think we need to always download an image. 
We don't have to use the image, but for the moment I'm using the Quarkiverse image and using it. Therefore, by happy chance, this resolves #41.
=> Error tolerance: download backup image to keep remote images plugin happy

gatsby-node.js, gatsby-node.test.js, src/maven/maven-info.js, src/maven/maven-url.js
We're seeing a lot of problems where maven central is returning 504s when we try and confirm URLs exist and get release timestamps, This is only a minor workaround, but take steps to make sure that maven errors don't confuse gatsby.
=> Improve maven tolerance

test-integration/links.test.js
The asyncapi dead link will hopefully be fixed by publishing the docs.
=> Ignore jpastreamer link error while we wait for a new release

src/components/util/extension-slugger.js, src/components/util/extension-slugger.test.js
That is, more folders, fewer dashes and underscores. I thought this would create problems in implementation and interpretation, but I implemented it, and maven central use the same convention, so interpretation should also be fine.
Fixes #52
=> Move to maven-central-style path formatting 

gatsby-config.js, gatsby-node.js, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, src/templates/extension-detail.js
Changed the type of the ‘extension’ nodes I was creating to ‘Extension’, since type names should be Pascal case. This means the type is actually applied, instead of being defined but never applied to the nodes I was creating.
This rippled through quite a few places in the codebase. The main effect of this is that all the schema I was defining actually are applied to the extension nodes.
A code path that wasn’t being traversed, for reasons I couldn’t figure out, now is being traversed. It turned out to not be a great way of doing the thing, so I removed it. I also removed a bit of clutter from the starter.
=> Correct case of name of extension type to be consistent

gatsby-config.js
Now that #59 is fixed, we can remove comments about it. Error suppression never seemed to work, but we probably don't want it.
=> Tidy comments

src/maven/maven-info.js, src/maven/maven-info.test.js, src/templates/extension-detail-page.test.js
Now that we are using the type hierarchy as intended, we can stop setting a dummy value for maven timestamps; it gets rendered as 1970, which looks silly :)
=> Use undefined for unknown maven timestamp 

__mocks__/gatsby-plugin-image.js, gatsby-node.js, src/components/extension-card.js, src/components/extension-image.js, src/components/extension-image.test.js, src/pages/index.js, src/templates/extension-detail-page.test.js, src/templates/extension-detail.js
This PR resolves #23 (except for a bit of documentation), and adds support for reading an extension image from a `logo` key in the metadata of the extension yaml. I couldn't try it with a published extension, but I've tested it with a dummy metadata and confirmed the code paths work as intended.
=> Check for logo key when deciding image, consolidate image selection logic

gatsby-node.js, src/components/extension-card.test.js, src/components/extension-image.js, src/components/extension-image.test.js, src/pages/index.js, src/templates/extension-detail-page.test.js, src/templates/extension-detail.js
When I was testing for SVG support, I spotted that I hadn’t got the key rename from ‘logo’ to ‘icon-url’ as correct as I’d thought, so I’ve fixed that.
=> Correct logo->icon-url key rename

gatsby-node.js, src/components/extensions-list.js
We already turn this into a slug, so we can use the slug, which is unique, for the extension id, instead of the name, which is not unique.
Resolves #73
=> Use group id and name from gav for extension ids 

.github/workflows/build_and_publish.yml
Since this site is static, we need to run regular builds to keep the content current. This sets up a daily build at 3am. 
@gsmet, I'd welcome your opinion on whether this seems like a good time of day and frequency (not too wasteful, but fresh enough?) ... and also on whether you think I got the syntax right.
=> Set up scheduled builds

src/components/navigation.js
This was hard to spot for a Quarkus dev who has visited all the links, but I noticed it when I tried a different browser.
=> Fix issue causing unvisited links to show as blue 

gatsby-config.js, src/components/hero-bar.js, test-integration/frontpage.test.js
This updates the hero bar to the style used on the main site, in partial resolution of #47. @insectengine says the hero bars may be going away across the whole site, so this section of code may be short-lived anyway.
=> Update hero bar to main site style

src/components/extensions-display/breadcrumb-bar.js, src/components/extensions-list.js, src/components/footer.js, src/components/hero-bar.js, src/components/navigation.js, src/style.css, src/templates/extension-detail.js
This PR improves the re-use and naming for the side-margin values. 
Once we have consolidated values, we can put media queries in `styles.css` to align the shrinking of the margins with quarkus.io.
=> Responsive margins

src/components/headers/submenu.js
The issue happens when trying to move onto the menu after it's been highlighted. It had been fixed by putting lots of padding on the menu titles, but that made alignment with the main site hard. When I adjusted the padding in #88, the menu behaviour regressed. 
I've instead put the extra 'grip' on the menu itself, which should be more resilient in the face of other spacing changes.
=> Correct issue causing us to sometimes 'fall off' the hover menu 

test-integration/links.test.js
The links checker will update links of the form /extensions/whatever to /whatever. In doing so, after #90, it was removing any instance of the word 'extension' in a URL. This led to false positives in the test. 
I initially adjusted the path prefix to add slashes, but other parts of the gatsby codebase use it. I think there's a risk stripping the prefix could cause problems where we link to `/extensions`, which would actually be `/extensions/extensions' when deployed, which is a dead link, but the link checker wouldn't catch it. So I've just removed that adjustment from the test.
=> Links test should not rewrite links to make them broken

.github/workflows/build_and_publish.yml
Resolves #32 (again). We had a guard on deploy that did not include scheduled builds.
I also noticed after the repo rename, deploys stopped entirely, so this updates a hardcoded repo name to get them going again.
=> Deploy on scheduled builds, and update hardcoded repo name 

.github/workflows/build_and_publish.yml, .github/workflows/preview.yml
The surge preview needs it and cannot …find it other ways (which is surprising).
Resolves #49 .
=> Store PR id after build, to pass to preview build

gatsby-node.js, gatsby-node.test.js, src/components/extensions-display/code-link.js, src/components/extensions-display/code-link.test.js, src/components/util/code-quarkus-url.js, src/components/util/code-quarkus-url.test.js, src/components/util/pretty-platform.js, src/components/util/pretty-platform.test.js, src/style.css, src/style.js, src/templates/extension-detail.js
This also includes logic to construct code.quarkus.io urls in a smarter way than just adding a `?e=whatever` query parameter onto the url... so it ended up being a larger code change than originally envisioned. T
I've reviewed the visuals with @insectengine. 
This is the logic for urls, to hopefully avoid the situation where people following a link get a message that the extension isn't available: 
- If a platform extension isn't available in one of the three current releases, we don't show a button
- If an extension is unlisted, we don't show a button
- For non-platform extensions we show a button, with a simple query parameter, made from the group id and artifact id
- For platform extensions, we pass in the 'short form' extension name and also the stream it is in. That fixes the problem …
=> Add "try this extension" button

src/maven/maven-info.js, src/maven/maven-info.test.js, src/maven/maven-url.js, src/maven/maven-url.test.js
We used to use maven search but maven gives us a lot of 429s and 504s, which means we do not have complete date information. We can get the headers for the artifacts directory instead. In my local testing this wasn't wildly more reliable than the other technique, but having two places to check has to be better than relying on a single, rather fallible, point of failure. 
If this does not give us consistent dates we will need to resort to github actions caching. 
Resolves #75.
=> Use artifact directory last-modified header as the primary source of timestamp

src/components/extensions-list.js, src/components/extensions-list.test.js, src/pages/index.js
Partial resolution of #76. We now don't show cards where there is duplicate with relationship 'newer'. I've added tests to make sure that if the relationship is 'different', we *do* show the card, because we don't know which one is the current card. 
These are the extensions which have been de-duplicated:
```
0: Object { name: "Reactive HTTP and WebSocket Connector" }
1: Object { name: "Neo4j client" }
2: Object { name: "JSch" }
3: Object { name: "Artemis JMS"}
4: Object { name: "Artemis Core" }
5: Object { name: "Apache Tika" }
6: Object { name: "Amazon Alexa" }
```
=> Do not show cards for extensions which have been superseded.

gatsby-node.js, gatsby-node.test.js, src/components/extensions-list.js, src/components/extensions-list.test.js, src/pages/index.js, src/templates/extension-detail.js
Resolves #75. 
Clicking the 'next' and 'previous' links should never take you to a superseded extension. If you're on the page for one, the next and previous links should work normally.
=> Do not include superseded pages in next and previous links

.github/workflows/build_and_publish.yml, README.md, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js
This should enable source control information to appear in the UI in surge previews. (At the moment those previews cannot get any information from the git API.)
This also solves the problem of token rotation, at least for the github tokens. Surge tokens may need rotation still, but we will worry about that later.
Resolves #50.
=> Use git-provided token instead of a secret

src/components/filters/search.js
Resolves #98. For accessibility reasons, I didn't want to completely remove the focus outline, but it didn't look good where it was. The main quarkus.io site has a blue outline on the outside of the search box, so I replicated that. I couldn't exactly replicate the colours – and they would have looked different anyway, because the background color is different – so I used quarkus blue.
=> Move blue highlight on selected input to outside edge of search box

gatsby-node.js, package-lock.json, package.json, src/components/filters/dropdown-filter.js, src/components/filters/dropdown-filter.test.js, src/components/filters/filters.js, src/components/filters/filters.test.js, src/components/filters/version-filter.js, src/components/filters/version-filter.test.js, src/pages/index.js
Resolves #103.
Convert built with quarkus core field to camel case, so it shows up in graphql (and therefore in the UI) 
Once that was done, it became obvious there were a *lot* of entries in the menu, so they needed sorting. Because these are versions, it needed a proper version-aware sort, not a simple lexographic sort. I had to try a few version comparison libraries to find one that correctly handled the maven format (`.Alpha`, `.Final`, etc).
The field name "Quarkus Version" isn't actually a great fit for what's in the field, which is the specific version that it was built with. I've renamed it to "built with" and raised #140 to cover the scenario of allowing people to filter by compatibility.
=> Populate "Quarkus Version" menu by bypassing graphql issues caused by slashes in field names

gatsby-node.js, gatsby-node.test.js, package-lock.json, package.json, src/templates/extension-detail-page.test.js, test-integration/links.test.js
A recent change in the registry seems to have exposed https://stackoverflow.com/questions/74566024/axios-get-returns-non-readable-response. It seems axios recently changed the default for its accept header to default to gzip. The Gatsby code is extremely unhappy at getting a gzip back. 
I have a few ideas about what triggered it: - The Quarkus version change (https://github.com/quarkusio/registry.quarkus.io/pull/173) made Quarkus more willing to honour the (unhelpful) protocol request from axios - https://github.com/quarkusio/registry.quarkus.io/pull/92 doubled the size of the response, which made Quarkus more willing to send back a gzip
In either case, the problem can be resolved by updating to the version of axios that doesn’t have the bug/behaviour. 
Once that is done, a second …
=> Resolve build break caused by recent registry update

src/components/util/pretty-platform.js, src/components/util/pretty-platform.test.js
Now that we (once I fix the dead links) show non-core platforms, we're discovering some gaps in the pretty-printing of platform names. I've updated the mapping logic to turn the verbose names we were generating into more human-friendly names with a higher signal-to-noise in the dropdown. 
*Before*
*After*
=> Improve platform name rendering for non-core platforms

src/components/extension-card.js, src/components/extensions-display/code-link.js, src/components/extensions-display/extension-metadata.js, src/style.css
Resolves #25.
To fix crowding on the extension detail page, I relaxed the requirement that all rows be the same height. 
Fixing overflow on the cards took a bit more thought. Getting ellipses to show on a single line of text is straightforward, because there’s a well-supported css property for it. For multi-line text, it’s less obvious what the right solution is. I didn't want to do pre-processing of the actual data before rendering, because it would require a lot of assumptions about text size and character width and seemed error-prone.
I started working through the instructions in https://css-tricks.com/recreating-mdns-truncated-text-effect/ and it was looking quite smart, with a neat fade on the quinoa card. It was a bit fiddly, though, so it would have needed a fair bit of debugging …
=> Fix text overflow on extension cards and extension detail pages

src/components/extension-card.js, src/components/extension-card.test.js
This should help eliminate any confusion about why such extensions (when they pop up from a direct search) are grey. 
Resolves #118.
=> Add a line saying unlisted extensions are unlisted

src/components/extension-card.js
Resolves #97. 
- I reproduced the text truncation logic from #25 from the description to the name. 
- I nudged the card width up to 240px from 220px, and that allowed me to get most extension names into 2 lines. With the narrower width and the current font-size we were losing a lot of space to wrapping. Many of the camel extensions, like Camel Async HTTP Client (AHC) Websocket, or Camel AWS 2 Managed Streaming for Apache Kafka (MSK) have ridiculously long names, so they still overflow.
- I kept the logo the same size, but reduced the padding below the logo. @insectengine, let me know if you think it looks too cramped. 
- I also reduced the padding around the various text blocks, since it’s unusual for an extension to have both an ‘unlisted’ flag *and* a long description. So only in a very …
=> Make text on extension cards shorter and denser

gatsby-node.js, gatsby-node.test.js, src/components/extensions-list.js, src/components/extensions-list.test.js, src/components/filters/category-filter.js, src/components/filters/filters.js, src/components/filters/filters.test.js, src/pages/index.js
Resolves #104.
I’ve updated the categories filter to sort by the number of extensions with that category, in descending order. As part of this change, I have moved some of the ‘counting what categories and platforms we have’ logic from the front-end to the back-end, which may help performance a bit.
=> Sort category filter by number of extensions in each category

src/maven/maven-url.js, src/maven/maven-url.test.js, test-integration/links.test.js
Resolves #157 . We could use the new URL or we could block the redirect. The old URL will [eventually be deprecated](https://central.sonatype.org/faq/what-happened-to-search-maven-org/), so we may as well start using the new URL.
=> Use new-style maven central URLs

src/components/util/code-quarkus-url.js, src/components/util/code-quarkus-url.test.js, src/components/util/pretty-platform.js, src/components/util/pretty-platform.test.js, src/templates/extension-detail.js
Resolves #161. We assume most platform extensions we list were in the last recommended stream of the platform, and so we omit the platform when creating code.quarkus links. This means we don't push people onto creating alphas. 
Example good case:
https://extensions-quarkus-pr-177-preview.surge.sh/io.quarkus/quarkus-agroal gives a link https://code.quarkus.io/?e=agroal
The downside is for some extensions, the code.quarkus.io links no longer work correctly. Example bad case:
https://extensions-quarkus-pr-177-preview.surge.sh/io.quarkus/quarkus-azure-functions
=> Use recommended stream instead of alpha in code.quarkus links

plugins/github-enricher/gatsby-node.js
There was a guard, but it was not the right guard. 
The right fix is a promise retry or maybe a more efficient query, but in the short term, at least don't break the build.
=> Do not crash out if we hit the GitHub rate limiter

src/templates/extension-detail-page.test.js, src/templates/extension-detail.js
This is on the extension detail page. As discussed with @maxandersen 
Before:
After:
=> Change Version to Latest Version to make it clear it is not necessarily recommended

__mocks__/test-data/quarkus-repo-listing-from-graphql.json, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/labelExtractor.js, plugins/github-enricher/labelExtractor.test.js
Some directories in the labelling rules have several sub-folders, and it's those folders whose name we need to look at. I've used the GitHub GraphQL api to grab the directory listing so I can work out those directory names, and extended the searching to include them. 
This catches several more extensions that weren't getting the label correctly identified. There are still some we miss, in some cases because of the rules (which I've raised a PR for), and in some cases because we just don't have a label. 
However, as the rules evolve, our accuracy will improve. 
Resolves #44.
=> Also look at the names of folders inside the folders listed in the rules

test-integration/links.test.js
I've also re-increased concurrency a bit to increase build speed (currently glacial).
Now that we have more github repos to check, we are seeing a lot of 429s from GitHub, which is affected overall build stability.
=> Use linkinator config which retries on 429

gatsby-node.js, src/components/util/guide-url-rewriter.js, src/components/util/guide-url-rewriter.test.js, test-integration/links.test.js
In some cases, the guide links in the extension yaml go out of sync with what's live on the internet, because the two sources evolve at different rates. In some cases, this is a dead link, but sometimes we can resolve the impedance mismatch by patching up the link. 
Resolves #155.
=> Rewrite guide links to avoid dead links for lapsed or hot-off-the-press extensions

src/components/filters/dropdown-filter.js, src/components/filters/dropdown-filter.test.js, src/components/filters/filters.test.js
=> Add 'all' option to dropdown menus which clears selections

src/components/filters/filters.js, src/components/filters/filters.test.js, src/components/filters/status-filter.js, src/components/filters/status-filter.test.js, src/components/util/compare-status.js, src/components/util/compare-status.test.js, src/pages/index.js
I've removed the "Built with" filter until we can do one or both of
- Have a more complete compatibility filter
- Have a filter which queries across multiple versions of each extension
See discussion in #198. 
That started to look lonely in the sidebar, so I've implemented #146. (This resolves #146.)
=> Remove "Built with" filter

src/maven/maven-url.js, test-integration/links.test.js
We have had persistent failures for a few days, because some extensions are not listed in http://sonatype.central. They are in http://search.maven. The pages were returning 500 for a few days and are now returning 404, so seems like there was a publishing glitch during a time window which caused sonatype central not to update. 
Rather than whitelisting the dead links to make the build pass, we can fallback to the old style links. 
These are the affected extensions:
```
"https://central.sonatype.com/artifact/io.quarkiverse.amazonalexa/quarkus-amazon-alexa/2.0.0/jar => 404 (Not Found) on http://localhost:9000/io.quarkiverse.amazonalexa/quarkus-amazon-alexa",
+   "https://central.sonatype.com/artifact/io.quarkiverse.tika/quarkus-tika/2.0.0/jar => 404 (Not Found) on …
```
=> Use search.maven when central.sonatype links are dead

.github/workflows/build_and_publish.yml, .gitignore
This allows to trigger the publishing anytime without waiting for the next cron job trigger to be fired
=> Adding `workflow_dispatch` trigger to Gatsby Publish workflow

src/components/extension-card.js, src/templates/extension-detail.js
Now that #105 is done, the square edges on dark-background imges don't look right.
Before: 
After:
I've also updated the image on the extension details page.
=> Round corners so logos with dark backgrounds look ok with new card shape

src/components/extension-card.js, src/components/extensions-list.js, src/components/filters/category-filter.js, src/components/filters/title.js
Resolves #201. 
I also nudged the font size down in the extension description, the category list, and the headers in the filters. 
I’ve made the card width flexible, and also the height. In practice it doesn’t adjust the height much because extensions like Quinoa, which have long descriptions, always force it to the maximum of the range. 
Note that sometimes within cards, the top of the descriptions aren’t aligned across cards. Under the covers, this is because the title divs have shrunk. This slightly raggediness allows us to shrink the cards if the only cards being shown have short titles. 
Note also that card height is consistent within a row, but does vary between rows. This gives much higher density, and @insectengine and I think it looks ok. 
Things to try when reviewing: 
- Various …
=> Improve responsiveness of extension cards to pack space better on smaller screens

src/components/util/guide-url-rewriter.js, src/components/util/guide-url-rewriter.test.js
We are seeing failures because kogito is not in the 3.0 platform, so short-form guides links do not work. Longer term, we want something like https://github.com/quarkusio/registry.quarkus.io/issues/188, but in the tactical short term, we can extend the existing url mapping to handle this case. Unlike for the camel guide links, we need to hardcode what version to guess. 
```
Array [
+   "https://quarkus.io/guides/kogito => 404 (Not Found) on http://localhost:9000/org.kie.kogito/kogito-addons-quarkus-jobs-service-embedded",
+   "https://quarkus.io/guides/kogito-dmn => 404 (Not Found) on http://localhost:9000/org.kie.kogito/kogito-addons-quarkus-events-decisions",
+   "https://quarkus.io/guides/kogito-pmml => 404 (Not Found) on http://localhost:9000/org.kie.kogito/kogito-addons-quarkus-events …
```
=> Check n - 1 version if a guides link does not exist

plugins/github-enricher/gatsby-node.js, test-integration/links.test.js
The CI build (but not the local one) is failing with 
```
error "github-enricher" threw an error while running the onCreateNode lifecycle:
Cannot read property 'issues' of null
253 |           repositoryOwner: { avatarUrl },
254 |         },
> 255 |       } = body
|           ^
256 |
257 |       const allMetaInfs = [
258 |         ...(metaInfs ? metaInfs.entries : []),
```
This is a classic 'this should never happen' error, but let's guard-and-log.
=> Add guard on github response destructuring

.github/workflows/build_and_publish.yml
This also removes an exemption for a dead guide link which is now sorted out.
=> Bump action version for setup node

plugins/github-enricher/gatsby-node.js
Follow on from #245, now that we know why the response data is sometimes null.
=> Check for errors explicitly rather than getting confused.

src/components/util/guide-url-rewriter.js, src/components/util/guide-url-rewriter.test.js, test-integration/links.test.js
See discussion in https://github.com/apache/camel-quarkus/issues/4964. Although the camel docs links do not point to the ideal branch, there is a ‘next’ docs link that we can use if docs are not available on one of the other branches.
=> Use snapshot docs links as fallback if camel docs are not available in the link for the current version

src/components/headers/navigation.js
I noticed the publications link is dead. I don’t understand why the links test didn’t catch it, it’s exactly the kind of problem it’s for. 
While checking that, I realised that the main site’s navigation has changed, and Publications and Events have gone, and Roadmap has appeared. So I've mirrored that into the navigation here.
=> Update menu items in Community header

src/components/headers/navigation.js
Now that we have an external Quarkiverse hub, we should add it to our navigation menus 
- so people can navigate to it
- so search engines index the hub pages
Following the convention in the 'Extensions' menu, it should be a verb. The best I could come up with to describe what people would do on the hub was 'Publish'. 
If this menu's ok, I will mirror it across to the main site and to the quarkiverse docs.
=> Add Quarkiverse hub to navigation menu

src/style.css
Avoid having :visited as a different color.
Make navigation links consistent with the description links.
=> More consistent link colors

gatsby-config.js
The remote images plugin has (sort of) been updated to add an option to not try and download undefined images. This is good, because the stack traces from the attempts are generating huge amounts of noise in the build logs. 
Sadly, the update doesn't quite work, so this change won't improve our logs until [remote-images-#169](https://github.com/graysonhicks/gatsby-plugin-remote-images/pull/169) is included in a release, but at least we'll be ready when it is.
=> Use new config option to avoid annoying stack traces in log

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, src/templates/extension-detail.js
We have a lot of errors in the log from querying GitHub about malformed gitbox URLs. These are currently used by Camel, and are of the form "https://gitbox.apache.org/repos/asf?p=camel-quarkus.git;a=summary".
- If we don't have a GitHub project, we shouldn't ask GitHub about it. 
- If we can't get a good reply from GitHub, but we have a URL, we should display it 
For the URL to display, I had to implement a fallback for the github project, which is used as the link text. For Camel, we could parse out the project name from the gitbox link, but if we were going to do that we might as well just parse the whole gitbox link and query the GitHub information. I haven't taken the time to do this since I believe the next Camel release will be using GitHub URL links.
=> Improve SCM url handling for Camel (and other non-GitHub repos)

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js
We're seeing some grey icons for extensions whose URL we definitely know (so we should be able to work out an image). The issue is likely caused by the GitHub rate limiter (despite retries and backing off). 
We would ideally cache information between Actions runs (#276), using the Gatsby cache facility and the GitHub actions cache facility, but a simpler solution will get us quite a lot of the way; for repos like camel and quarkus, we don't need to query the repo for each extension that lives in it. 
The two exceptions are 
-  issue counts for quarkus, because we use labels to narrow down the issues to the relevant ones
- extension-specific directory listings (we look for subfolders with the artifact id in the name, to try and find the quarkus-extension.yaml so we can link to it)
Even if …
=> Cache github information about the same repository

.github/workflows/build_and_publish.yml, package-lock.json, package.json
This should reduce log noise, pending https://github.com/graysonhicks/gatsby-plugin-remote-images/pull/169.
I've also updated the upload-artifact plugin to resolve a build warning.
=> Use fork of gatsby-plugin-remote-images 

.github/workflows/build_and_publish.yml, .idea/codeStyles/Project.xml, package-lock.json, package.json, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/persistable-cache.js, plugins/github-enricher/persistable-cache.test.js
Resolves #276. We are having API requests to GitHub blocked by the secondary rate limiter, so we need to cache more.
=> Write node cache to Gatsby cache and use GitHub cache to persist Gatsby cache to avoid grey images

gatsby-node.js, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js, src/templates/extension-detail.js, src/templates/extension-detail.test.js
Resolves #18 
Here’s what’s implemented:
If someone has set a sponsor: field in the extension yaml, that will be shown in the UI. 
Otherwise, *if* we’re quite confident that a company is a main contributor to an extension and they’ve opted in, we will automatically identify them as a sponsor and show them in the UI. 
Here are the rules for ‘quite confident’:
- Has more than one contributor on the project
- Has made more than 5 commits in the past six months
- The company is responsible for more than 20% of the commits
This is conservative, so we will miss some sponsors. In those cases, the extension metadata can be updated.
The opt-in is done by edits to quarkiverse/quarkiverse, and the file is named-contributors-opt-in.yml ([PR](https://github.com/quarkiverse/quarkiverse/pull/182))
If …
=> Show 'maintainer' field on extension details page

.github/workflows/build_and_publish.yml, .github/workflows/preview.yml
The Gatsby Publish builds are failing:
```
fatal: could not read Password for 'https://***@github.com': No such device or address
```
I think the issue is that the personal access token we were using has expired. Instead of using a PAT, which is a maintenance burden, some of our other sites use a different gh pages deploy action, that doesn't need a PAT. As a bonus, it also doesn't rebuild the site. 
We do need to fuss with path prefixes a bit on the preview side, but this is a small inconvenience.
As usual, all the preview can test is the preview, not the actual deploy.
=> Fix deploy break

.github/workflows/build_and_publish.yml, gatsby-config.js, package-lock.json, package.json, src/analytics/segment-snippet.js, src/analytics/segment-snippet.test.js, src/analytics/segment-snippet2.js, test-integration/frontpage.test.js
We would like to understand usage of the extensions site, for a few reasons:
- Get an extra indicator of Quarkus usage
- Understand how valuable the extensions site itself is
- Get an indicator of which extensions attract the most interest
Segment is being used elsewhere for Quarkus analytics, so we should use that. However, we want to make sure to use it in a privacy-preserving way. I think a cookie popup for such a simple, non-commercial, site would be a bad user experience. 
We also don’t want to track users without consent, because that would be a GDPR violation. We don’t have any reason to track users; there’s some value in identifying unique users, but respecting user privacy and a good user experience is (IMO) more important. 
I’ve looked at the …
=> Add segment analytics

.github/workflows/build_and_publish.yml, .github/workflows/preview.yml
#322 managed to mess up both relative paths and the comments for the previews. A much better solution to the fact that the preview has no path prefix and the main deployed site does is to just conditionally pass the `--prefix-paths` argument, depending on which mode we're building for; we never do both a preview and a deploy from the same binary artifact.
=> Fix preview

.github/workflows/build_and_publish.yml, jest-puppeteer.config.js
The integration tests also need to be run with the same path prefix setting as the build.
=> Fix mainline-build integration tests

.github/workflows/build_and_publish.yml
We currently have two problems: 
1. Why don't the integration tests work with path prefixes in the way the docs say?
2. Why is the live site still not using the path prefixes, despite clearly being built with them?
https://www.reddit.com/r/gatsbyjs/comments/edihq5/why_is_prefixpaths_breaking_my_build_during/ suggests cleaning may help problem 2.
=> See if a clean sorts out the path prefixes

.github/workflows/build_and_publish.yml
... and also guard integration tests to only not run in the 'main' scenario, where the `gatsby serve` hangs.
=> Try deploying in same step as build

.github/workflows/build_and_publish.yml, gatsby-config.js, jest-puppeteer.config.js, test-integration/frontpage.test.js, test-integration/links.test.js
It turns out #338 was caused by not having a leading slash on the path prefix config. With that fixed, a few other fixes were needed to the integration tests so they looked in the right place for liveness and for the base application. 
Sadly, the path prefix path of this can only be tested after merging, but I've tested locally and it seems good.
Resolves #338.
=> Add leading slash to fix gatsby serve with path prefix

src/templates/extension-detail.js, src/templates/extension-detail.test.js
Sort of resolves #340. The actual example shown in #340 is a later date, something like 1692338000, but I don't think we want to try and filter those out, since they're less obviously wrong than 0.
=> Do not render '0' dates

.github/workflows/build_and_publish.yml
Resolves #337. 
I don't know how the other download action was working, but I think this explains why there was stale content - we were uploading artifacts only on PRs, and then trying to download them on the main build. That's pretty disastrous.
=> Upload artifacts on every workflow, since we use them on every workflow.

src/templates/extension-detail.js, src/templates/extension-detail.test.js
=> Do not show a label for a source control link if there is no link

gatsby-config.js
It was removed as part of the debugging of #337, but in fact it wasn't the cause of the problem.
=> Reinstate segment plugin

.github/workflows/build_and_publish.yml, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/persistable-cache.js, plugins/github-enricher/sponsorFinder.js
We're still seeing a lot of rate limiter warnings in the build logs, which cause data (sponsors, extension icons, etc) to not be populated. 
To improve things, I've: 
- Switched the scheduled build to run twice a day, rather than once. This should mean the number of expiring items in each run is smaller. 
- Lengthened the time to live from 2 days to 3 days
- Increased the amount of jitter on the ttl
- Increased the gap-before-retry and retry scale factor for the retry calls on the GitHub API. This will slow down builds, but seems to improve the amount of data we get. 
Some data is refreshed every build, so the last change is perhaps the most effective one.
=> Ease GitHub rate limiter issues by caching longer and retrying slower

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/github-helper.js, plugins/github-enricher/github-helper.test.js, plugins/github-enricher/persistable-cache.js, plugins/github-enricher/persistable-cache.test.js, plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js, test-integration/links.test.js
Debugging the rate limit issues and caching is a bit tricky, partly because the code for accessing the github api has got a bit sprawling and duplicated. Consolidating, which makes it much more readable, and also helps the tests.
=> Consolidate GitHub calls to improve code clarity

.github/workflows/build_and_publish.yml, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/github-helper.js, plugins/github-enricher/github-helper.test.js, plugins/github-enricher/sponsorFinder.js
#352 introduced a bug into the retry logic for the graphQL API, so that needs fixing. 
The Gatsby/GitHub caching also doesn't seem to be behaving as expected, so I've put in a few awaits (all promises are caused by missing returns) and also some diagnostic logging. The Gatsby cache is expected to be wiped on things like package.json changes and core file changes, but we're seeing something more consistently ineffective.
=> Fix bug in promise retry, wait for caches to see if that helps

.github/workflows/build_and_publish.yml, plugins/github-enricher/github-helper.js, test-integration/detail-page.test.js, test-integration/frontpage.test.js, test-integration/links.test.js
We're continuing to see pages with incomplete or totally missing GitHub data being published, so I've added an integration test to try and block these. 
I've also corrected a missing retry in the retry logic for github fetches.
=> Fix GitHub retry logic and add integration tests for page details

.github/workflows/build_and_publish.yml, .gitignore, package-lock.json, package.json, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/persistable-cache.js, plugins/github-enricher/persistable-cache.test.js, plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js, test-integration/detail-page.test.js, test-integration/links.test.js
When we started working on caching between builds, we debated whether to use the built-in Gatsby cache or a self-managed one. We decided that the Gatsby one had several advantages; it meant no new dependencies, the cache could be cleaned with `npm run clean`, and in general leveraging existing mechanisms seemed like a good thing.
However, we're now seeing disadvantages, the main one of which is that caching just doesn't seem to work in the CI. It works locally, but in the CI, the report about what's ingested from the cache is always zero. I think this might be because Gatsby will flush the cache if package.json or gatsby config or gatsby-node files are changed, and perhaps the timestamps from the checkout confuse that condition. 
I'm also seeing really puzzling behaviour with #347, which …
=> Switch from Gatsby cache to self-managed cache.

plugins/github-enricher/github-helper.js, plugins/github-enricher/github-helper.test.js
We sometimes see failures on the fetch of the raw files, so we should wrap that in a retry, too.
=> Apply tolerant fetch to getting raw files, too

plugins/github-enricher/sponsorFinder.js
Some companies aren't showing as sponsors, and I think it's because a space has snuck into an `@` name.
=> Add missing normalisation of company name

src/components/extensions-list.js, src/components/util/extension-comparator.js, src/components/util/extension-comparator.test.js
This isn't as good as a proper customisable sort with options for popularity and affinities and possibly other categories, but I think date is a more natural sort order than alphabetical, and it's a quick update. I've used a one-hour granularity on the dates so that extensions which are released in the same group (such as the main quarkus extensions) get sorted alphabetically, rather than chronologically (since that just looks random).
=> Sort in descending date order

src/components/util/guide-url-rewriter.js, src/components/util/guide-url-rewriter.test.js, test-integration/links.test.js
See discussion at https://github.com/apache/camel-quarkus/issues/4964#issuecomment-1721499369. Because these artifacts appeared in a recent release, and then disappeared out of it before the final docs were available, our rule for checking the version doesn't work - and it wouldn't work for camel-format links anyway. Our n-1 rule also didn't work for camel format, so I've added a few variations for camel links.
=> Check LTS versions of camel artifacts

plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js
We were not correctly `await`ing the query to turn a user id into a company name, which affected our ability to show sponsors. This was aggravated by the fact that we were doing a case-sensitive comparison with the sponsors opt-in list. 
I've switched to doing a case-insensitive comparison, which should get sponsors showing immediately, and as the caches refresh it should switch to the correct capitalisation.
=> Correct sponsors logic

plugins/github-enricher/github-helper.js, plugins/github-enricher/github-helper.test.js, plugins/github-enricher/sponsorFinder.realdata.test.js
We noticed that the community tab is showing numbers that are too small for high-traffic repositories such as quarkus core, and also (for example) iron jacamar. The problem is that GitHub is only returning 100 commits per query. 
This change introduces pagination so we get full data. 
Sadly, the preview may not tell us very much, since data is cached. I've tested locally with an empty cache and am seeing correct counts for iron jacamar. For the main quarkus repo it cannot get data because of rate limiting, but hopefully with a warmed cache that problem will be less severe. 
Doing finer-grained queries of individual folders should also help with the rate limiting.
=> Paginate queries against the GitHub GraphQL API

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js, src/components/charts/contributions-chart.js, src/templates/extension-detail.js, test-integration/links.test.js
As suggested by @maxandersen, I've make contributor names on the contributor graphs hyperlinks, and removed the repeated 'commits' from the table on the right. This turned out to be a bit involved because I had to home-roll some elements recharts otherwise renders for us, but I think it's now looking as it should. 
I also spotted that once the cache is flushed and we pull all pages of github data, the main quarkus repo list is quite long, so I've added a scrollbar.
=> Link contributor profile from contributor graphs

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/sponsorFinder.js, src/templates/extension-detail.js
See #297
This has a few advantages: 
- It's more accurate
- Pulling down the whole six-month history of a big repo like quarkus needs about 10 paginated queries, and even with retries and backing off, we're seeing that the rate limiter is blocking us. This is then causing the integration tests to fail because we're not able to fill in issue counts for the test page. Doing more granular queries should allow us to build them up and gradually add them to the cache. 
The current logic also has some disadvantages:
- It excludes docs contributions
- If a few extensions share a parent pom, it excludes them
So another pass will be needed, but I think this is better than what we currently have.
=> Track contributors per-extension-path, not per repo

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/github-helper.js, plugins/github-enricher/persistable-cache.js, plugins/github-enricher/sponsorFinder.js
Caching the issue count is good to reduce how much we hit the GitHub API, and it also allows us to refactor the code related to caching the GitHub API and reduce the convoluted merge logic.
=> Cache issue count

.github/workflows/build_and_publish.yml, plugins/github-enricher/gatsby-node.js
I noticed that we're unable to find the metadata file for some camel extensions, so I've added cases for those to our path-finding query.
This improves result quality for these extensions, but should also slightly reduce a cascading failure we’re seeing - when we try to get all commits in a repo and fail, we try again for the next extension, which makes the rate limiter even more angry, so we definitely won’t succeed, and so on. Reducing the number of extensions where we try to get all the commits in a repo will help (although it’s not dealing with the root of the problem). 
It does mean overall the path-finding query is more expensive, but since we cache paths for a while, that should be ok.
=> Add some other camel cases for path-finding, and simplify logic

plugins/github-enricher/github-helper.js
Builds are failing, and I think it's because of trying to pull the full commit history of the quarkus repo. I can get it through locally, but the rate limiting is obviously not quite working out on the main build.
=> Slow down retries a bit

.github/workflows/build_and_publish.yml, plugins/github-enricher/github-helper.js, plugins/github-enricher/github-helper.test.js
Our strategy of blindly retrying with a long backoff isn't really working for us. 
Confusingly, I couldn't fully test this locally, because despite building three times with an empty cache, I never hit the rate limiter.
=> Be a bit smarter in how we wait for the github rate limit to refresh

plugins/github-enricher/gatsby-node.js
Otherwise, there are about 70 repos which we re-check every build.
=> Ensure we cache 'could not find' for extension yaml paths

plugins/github-enricher/github-helper.js, plugins/github-enricher/github-helper.test.js
I see now why #422 made the builds so fast - it broke pagination, because of a bug in the 'find the thing we should be paginating in the response' logic. I've updated the unit tests to reflect the new output and got everything passing.
With a clean cache, this is what I get running the change locally for one of the extensions where we don't know the exact path, like mariadb:
=> Correct pagination logic when rate limiting data is present in response

plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js, src/templates/extension-detail.js
I've compared against the GitHub UI, and my results seem to line up, except for a few small variations that could be caused by slight differences in the edges of the query time:
[GitHub results](https://github.com/quarkusio/quarkus/graphs/contributors?from=2023-05-07&to=2023-11-03&type=c)
My results
The results are different by 10 commits for [Ladislav Thon](https://github.com/quarkusio/quarkus/commits?after=31afcb20cd452f56e3d42c41998d9149ab3a9428+34&author=Ladicek&since=2023-05-07&until=2023-11-03),  which I can't explain and am a bit worried about, but I think overall the data is looking basically fine.
=> Exclude merge commits

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js
It will take the cache a while to warm up, and until it does we may show Red Hatters as 'other' incorrectly, so committing the back end before the front end.
See #297
=> Back end for showing contributing companies

.github/workflows/build_and_publish.yml
As well as changing the schedule to run three times a day in #422, I tacked on a 'trivial' change that broke the schedule. I thought I was setting it to run at 25 minutes past the hour, but instead I set it to run on the 25th of the month. Oops.
=> Correct cron schedule

.github/workflows/build_and_publish.yml, gatsby-config.js, gatsby-node.js
Resolves #304. We embed four weights of fonts as base64 strings in every extension detail page. 
With these changes, the unzipped size of the site goes from 297M to 70M.
=> Do not embed 3,276 base64 encoded font files in the index.htmls

plugins/github-enricher/sponsorFinder.js
See, for example, https://quarkus.io/extensions/io.quarkiverse.ironjacamar/quarkus-ironjacamar/?tab=community. Vincent doesn't have a company listed in his profile so we did not count his commits at all in the company chart.
Before:
=> Do not drop commits from tallies if a user does not have a company

src/templates/extension-detail.js
=> Include extension repo name in the case where we don't know the path

.github/workflows/check-external-links.yml, .gitignore, util/dead-link-issue.java, util/external-links.test.js
Partial resolution of #207 
When the dead link checker identifies dead links, we raise issues. We also look at issues we've raised and close them if the dead links are no longer present on the site, or dead. 
Ideally we would raise some issues, like dead guides, on the site of the owning extension, but that can be a next step.
=> Raise issues for dead links identified from test

plugins/github-enricher/gatsby-node.test.js
I apparently committed some `fit`s, which skip all other tests in the class. I'd like an automated check to prevent this, but my IDE doesn't seem to have one, and husky seems a bit heavy (and I'm not even sure if it could check for that, since google is not very helpful for this question).
=> Reinstate tests skipped in error

.github/workflows/build_and_publish.yml
The eslint step is now running, but failing with 
```
Warning: Unexpected input(s) 'all-files', valid inputs are ['github-token', 'eslint-args', 'extensions', 'annotations', 'root-dir', 'ignore-file', 'ignore-patterns']
```
=> Upgrade to try and resolve unknown argument error

.github/workflows/build_and_publish.yml
I thought it would be nice to get fast feedback on linting issues, so I put it early in the build, but that gives this error:
```
0:0 error Parsing error: [BABEL] /home/runner/work/extensions/extensions/.eslintrc.js: `babel-preset-gatsby` has been loaded, which consumes config generated by the Gatsby CLI. Set `NODE_ENV=test` to bypass, or run `gatsby build` first. (While processing: "/home/runner/work/extensions/extensions/node_modules/gatsby/node_modules/babel-preset-gatsby/index.js")
```
I've moved it later, which should sort out the failure.
=> Lint after gatsby build

util/dead-link-issue.java
See failure in https://github.com/quarkusio/extensions/actions/runs/6968685840/job/18964822495
```
[jbang] Building jar for dead-link-issue.java...
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: dead-link-check-results.json
at Report.run(dead-link-issue.java:83)
at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
at picocli.CommandLine.access$900(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
at picocli.CommandLine.execute(CommandLine.java:1904)
at …
```
=> Fix link checking happy path

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js
We risk having a problem where a company name gets excluded because the form in the opt-in doesn't quite match what we normalise the GitHub entry to.
=> Make sure to compare normalised names when deciding opt-ins

gatsby-node.js, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/repository-creator.js, plugins/github-enricher/repository-creator.test.js, src/templates/extension-detail.js, src/templates/extension-detail.test.js
As suggested by @maxandersen 
I've also moved the linting support to the top-level gatsby-node, since that seems like where I intended to put it in the first place. :)
=> Show how many extensions are in a repo on Community tab

src/templates/extension-detail.test.js
```
FAIL  src/templates/extension-detail.test.js
● extension detail page › for an extension with lots of information › has last updated information on the community tab
expect(received).toMatch(expected)
Expected substring: " 2024"
Received string:    "Commit statistics last updated Thursday, Nov 2, 2023, 11:25 AM."
227 |       expect(lastUpdated).toBeTruthy()
228 |
> 229 |       expect(lastUpdated.innerHTML).toMatch(" " + year)
|                                     ^
230 |
231 |     })
232 |
at Object.toMatch (src/templates/extension-detail.test.js:229:37)
```
=> Make test resilient to year changes by hardcoding date

plugins/github-enricher/gatsby-node.js, util/dead-link-issue.java
See, for example, https://github.com/quarkusio/extensions/issues/598. The issue is correct but the URL in it is wrong. With the current refresh rate, the problem on the live site might not get fixed for 10 days, which is far too long. We've also had several other dead yaml link issues lately.
=> Refresh yaml locations more often, and correct bad URL in raised defects

babel.config.js, jest.config.js, jest.integration.config.js, package-lock.json, package.json
Versions above Linkinator 2 are ESM rather than CJS, which causes problems in tests. It should be that Jest will transpile ESM to CJS, for everything except the content of `node_modules`. We can soften that exemption by including `linkinator` in the exclude in `transformIgnorePatterns,` but making that work was [non-trivial](https://stackoverflow.com/questions/71058618/to-have-some-of-your-node-modules-files-transformed-you-can-specify-a-custom/77753142#77753142).
I've got there in the end, and we can now add ESM dependencies as long as we update the config.
=> Use ESM extension on test to allow use of latest linkinator version

src/components/extensions-list.test.js, src/components/filters/filters.test.js, src/components/filters/search.js, src/components/filters/search.test.js
Resolves #212 
The solution to this wasn’t what I was expecting. The root cause is that pressing enter submits the form (it clicked when I read https://stackoverflow.com/questions/17281990/html-text-input-box-is-cleared-on-enter). Submitting a form doesn’t seem like a bad thing, but it appends the search text to the page’s query string and triggers a page reload, which then clears the text box. 
We can kill two birds with one stone by reading the query string, which will preserve the text (albeit with a flash), and also allow portable searches. The flash of the rerender was pretty annoying, so I also switched the input from being a form, to just being a div. Nothing actually needed the form, and the big re-render was too violent for a SPA.
=> Ensure 'enter' does not clear search text in filter box

plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js
We sometimes see log errors like the following:
```
warning Could not get GitHub information for https://api.github.com/users/apache @gigacloudtech - response is {"message":"Not Found","documentation_url":"https://docs.github.com/rest/users/users#get-a-user"}
warning Could not get GitHub information for https://api.github.com/users/migrationsverket @debezium - response is {"message":"Not Found","documentation_url":"https://docs.github.com/rest/users/users#get-a-user"}
warning Could not get GitHub information for https://api.github.com/users/bear-metal @Shopify @TuneMyGC - response is {"message":"Not Found","documentation_url":"https://docs.github.com/rest/users/users#get-a-user"}
```
These are caused by company fields like `@bear-metal @Shopify @TuneMyGC`. In this case, we should take the …
=> Handle case where company affiliations list several companies

gatsby-node.js
Mitigates #651. 
I'm having a hard time working around this issue, partly because every attempt in the CI is a four hour build while caches are populated, but also because the exception is coming from gatsby-image-sharp and I can't find a good point to `catch`. 
To get the CI on its feet again, we can just hardcode to drop the hive image before the other plugins see it.
=> Tactical fix to allow caches to be repopulated: just ignore hive icon

test-integration/detail-page.test.js, test-integration/frontpage.test.js
https://github.com/quarkusio/extensions/pull/650 did a good job of un-sticking a problem downloading the chrome driver, but it did a bad job of actually working. (We had to merge the PR untested, because the fix for https://github.com/quarkusio/extensions/issues/651 couldn't get through a build.)
Downgrading brings back the 500, so we will have to roll forward. 
● main site › when do not track is enabled › should have an extensions heading on it somewhere
TypeError: page.waitForXPath is not a function
97 |       await page.setExtraHTTPHeaders({ DNT: "1" })
98 |       await expect(
>  99 |         page.waitForXPath(`//*[text()="Extensions"]`)
|              ^
100 |       ).resolves.toBeTruthy()
101 |     })
102 |   })
at waitForXPath (test-integration/frontpage.test.js:99:14)
```
=> Handle removal of puppeteer API

src/maven/maven-info.js
I don't see this so much on the CI, but running locally, I get a lot of maven `ECONNREFUSED` errors, which kill the build. We have retries wrapped around most maven calls, but not the pom reading, so I've added one there. 
I've also added a catch so that if errors make it all the way through the retry, we don't halt the build.
=> Tolerate maven errors on pom reading

gatsby-node.js, gatsby-node.test.js, plugins/smart-cropper/gatsby-node.js, src/data/image-validation.js, src/data/image-validation.test.js
Mostly-solves #651, but leaving that open for the final piece, which is raising defects.
=> Validate images before creating remote file nodes

.gitignore, gatsby-node.js, site-validation/bad-image-issue.java
At the moment we do one per affected extension.
=> Limit issue creation to one per bad image

site-validation/external-links.test.js
Resolves #854 (if we're lucky).
=> Reduce concurrency of dead link checking to try and avoid 429s

site-validation/external-links.test.js
I've been puzzled that the defect raiser seems to be processing more dead links than the test is reporting; I think the issue is caused by a missing return, as all problems are. For the 429s, we do a slow process of retrying in an async callback, but we don't return the promise.
=> Make sure to return the promise from the async function

.github/workflows/build_and_publish.yml, README.md, gatsby-config.js, gatsby-node.js, package-lock.json, package.json, plugins/download-data/gatsby-node.js, plugins/download-data/gatsby-node.test.js, plugins/download-data/package.json, plugins/download-data/tableau-fetcher.js, plugins/download-data/tableau-fetcher.test.js, src/components/extensions-list.js, src/components/sortings/downloads-extension-comparator.js, src/components/sortings/downloads-extension-comparator.test.js, src/components/sortings/sortings.js, src/components/sortings/sortings.test.js, src/pages/index.js
I thought I'd have to do this by hand with manual uploads of download data, but I found the Tableau rest api and got it working. So this should stay current as long as we continue to get refreshes of the workbook and view we're using. Because it needs a secret for the Tableau access token, this won't render in the PR preview, but this is what I see locally:
The message about the date only shows when sort by downloads is selected. I've verified the order against the table in the Tableau UI. 
Partial resolution of #856. One problem is that we only have the artifact id, not the group id, in the raw data, so the json-logging downloads will get double-counted and can't be split (yet). I've raised #951.  
cc @maxandersen and @gastaldi, because this is a notable data enrichment.
=> Add ability to sort extensions by downloads, using Tableau download stats

src/components/sortings/sortings.js
Now that the Tableau data includes Camel downloads, the explanatory message needs to be a bit different.
=> Update message now that we have Camel data

gatsby-ssr.js, src/components/charts/contributions-chart.js, src/components/extension-card.js, src/components/extensions-display/breadcrumb-bar.js, src/components/extensions-display/code-link.js, src/components/extensions-display/extension-metadata.js, src/components/extensions-display/installation-instructions.js, src/components/filters/category-filter.js, src/components/filters/dropdown-filter.js, src/components/filters/search.js, src/components/filters/title.js, src/components/footer.js, src/components/headers/navigation.js, src/components/headers/submenu.js, src/components/headers/title-band.js, src/components/layout.js, src/components/sortings/sortings.js, src/components/util/copy-to-clipboard.js, src/components/util/styles/style.js, src/style.css, src/templates/extension-detail.js
See https://github.com/quarkusio/quarkusio.github.io/issues/1809 and https://github.com/quarkusio/quarkusio.github.io/pull/1908.
Allowing extensions to specify dark and light mode icons is a bit more involved, so I haven't done it in this change set. Most icons are OK, but the Quarkiverse ones have lost a bit of detail. 
I had to make up some of the greys that I couldn't read off the parent site, so some might need tweaking.
=> Dark mode support

src/components/extensions-list.js
Resolves #958. 
This seems to happen when the number of cards drops below a certain number, which is why the search triggers it. Filtering for the ‘core’ category also shows the problem.
I tried setting the max-height on the cards, but that didn’t help, because the grid was laid out the same, and the extra space was in the gutters. What seemed to solve the problem was undoing some nesting of containers, so I’ve done that. With that, I was able to very occasionally get huge cards, but only in the case where everything fit into one row. I’ve left in the max-height as a failsafe for that case.
=> Remove container nesting to avoid hyper-stretched cards

plugins/github-enricher/gatsby-node.js
Should sort out https://github.com/quarkusio/extensions/issues/992, although it will need to get through the cache.
=> Replace http github urls with https ones

src/components/extensions-display/extension-metadata.js, src/components/extensions-display/extension-metadata.test.js, src/pages/index.js, src/templates/extension-detail.js, src/templates/extension-detail.test.js
=> Include keywords in extension details page

src/components/extensions-display/code-link.js, src/style.css
I noticed that the 'try this extension' button on the extension details page has mostly-disappeared. It seems to have been a casualty of the dark mode work. I've put in a proper background colour and that's restored it.
=> Reinstate colour on 'try this extension' button, so it is visible

src/style.css, src/templates/extension-detail.js
It got lost in the refactoring for dark mode. 
Now: 
In dark mode, I couldn't get a good colour, so I went for grey:
=> Fix background colour on superseded warning

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, src/components/extensions-display/extension-metadata.js, src/components/extensions-display/extension-metadata.test.js, src/templates/extension-detail.js, src/templates/extension-detail.test.js
Resolves #1010 
We show a samples link if one is available. We special-case Camel and look for a suitably-named sample in the camel samples repository. We also special-case Quarkus and look in the quickstarts repository.
For example, 
- https://extensions-quarkus-pr-1011-preview.surge.sh/io.quarkiverse.langchain4j/quarkus-langchain4j-core/
- https://extensions-quarkus-pr-1011-preview.surge.sh/org.apache.camel.quarkus/camel-quarkus-kafka/
- https://extensions-quarkus-pr-1011-preview.surge.sh/io.quarkus/quarkus-hibernate-orm/
Open questions:
- Is "sample(s)" the best link name? I can't come up with a better one
=> Show link to sample folders where available

plugins/download-data/tableau-fetcher.js, plugins/download-data/tableau-fetcher.test.js
I noticed that the download data appeared to be working, but we were just seeing the fallback of the chronological sorting for all extensions. This turned out to be caused by a change in a header name on Tableau. 
I've fixed the local schema, and also updated things so that if the data isn't parsed properly, we don't enable the sort.
=> Correct schema, do not enable download sort if it is broken

.github/workflows/preview.yml
We get a clutter of skipped preview builds for scheduled builds, and I think we could bypass the triggering by adding a branch guard.
=> Do not trigger preview build on mainline builds

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/sponsorFinder.js, plugins/github-enricher/sponsorFinder.test.js, src/templates/extension-detail.js
When building outside the CI, only pull a single months worth of contributor data. This should keep the GitHub rate limiter a lot more happy, and avoid the three hour builds where most of the time is spent waiting for the rate limiter. 
The preview won't show anything, but locally I confirm I see shorter time periods:
In the CI builds, it should still be six months.
=> Speed up local builds by pulling less contributor data

.github/workflows/preview.yml
Previews are no longer running for scheduled builds, which is good, but they're also not running for PRs, which is bad. I can't find diagnostics about what the issue is, but syntax tweaks may help.
=> Tweak syntax to try and get preview build running again

.github/workflows/preview-teardown.yml
It's annoying to get comments on PRs saying a preview was torn down, if the preview was never created. 
Obviously, in most cases the preview *should* be there, but there are cases where it's not.
=> Do not comment on work items if teardown did not succeed

.github/workflows/check-external-links.yml, .github/workflows/preview-teardown.yml
Testing in production, https://github.com/quarkusio/extensions/actions/runs/9110926263
I've also taken the opportunity to move the link checking job to run in the middle of the night, since the current mid-day schedule is often inconvenient.
=> Correct workflow syntax

.github/workflows/preview.yml
Since merging https://github.com/quarkusio/extensions/pull/1020, previews are being done for dependabot PRs, but not personal ones. I don't understand why, but reverting to see if that helps get previews back.
=> Revert changes to not run preview on every build

site-validation/bad-image-issue.java, site-validation/dead-link-issue.java
I don't think this will fix https://github.com/quarkusio/extensions/issues/789, since there's an outstanding issue for the secondary rate limiter not being handled consistently, but it might help a bit.
=> Bump github api client to latest level

package-lock.json, package.json, plugins/github-enricher/gatsby-node.js
We see intermittent issues being raised, and then closed, for dead links for Debezium and Optaplanner issues. I had some difficulty reproducing locally. I think that explains #633; sometimes, the bad links are not shown, but sometimes they are. I think the intermittency happens because I do the validation in a promise and then set a variable outside the scope of that promise from inside the promise. 
The reason we are counting redirects as valid is because that's how `url-exists` works (but *not* how linkinator works). For now, I've counted redirects to `/pulls` as invalid. If we see other redirects, we can decide how to handle them. 
Resolves #1059. Resolves #633.
=> Do not show issue links which redirect to /pulls

.github/workflows/preview.yml
Previews aren't working anymore, because it seems to be trying to use the wrong artifact from a non-PR run for the preview,
=> Be more specific about preview run id

.github/workflows/build_and_publish.yml, .github/workflows/check-external-links.yml
All builds are failing with 
```
Pull down action image 'ghcr.io/jbangdev/jbang-action:0.116.0'
Error: Docker pull failed with exit code 1
```
=> Revert to previous version of jbang action

.github/dependabot.yml, .github/workflows/preview.yml
According to https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories, it is now possible to use the official download action to download results from other workflows, as long as a github token is specified.
=> Use official download action

site-validation/bad-image-issue.java, site-validation/dead-link-issue.java
The build is still being hit by rate limiting, even with what I hoped were fixes to the GitHub API. While I debug, use `HEAD` snapshots to avoid file churn.
=> Use `HEAD` of forked GitHub api

babel.config.js
Loose mode triggers a huge volume of warnings in the build logs; it also risks slightly broken semantics, potentially, 
```
warning Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-transform-class-properties since the "loose" mode option was set to "true" for @babel/plugin-transform-private-property-in-object.
The "loose" option must be the same for @babel/plugin-transform-class-properties, @babel/plugin-transform-private-methods and @babel/plugin-transform-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-transform-class-properties", { "loose": true }]
to the "plugins" section of your Babel config.
```
=> Do not use babel loose mode, to resolve warning

site-validation/bad-image-issue.java, site-validation/dead-link-issue.java
I think I was maybe looking at a stale build when I decided my fork of github-api still had a problem with 429s, since it now all seems to be working. Going back to a locked version.
=> Lock version of GitHub API in fork

gatsby-browser.js
Fixes #999 
https://medium.com/@fabianterh/fixing-flashing-huge-font-awesome-icons-on-a-gatsby-static-site-787e1cfb3a18 has a discussion of this, and https://github.com/FortAwesome/react-fontawesome/issues/134 has discussion specific to the react-fontawesome plugin we are using.
https://github.com/FortAwesome/react-fontawesome/issues/134#issuecomment-392078079 seems to be the most helpful comment. 
Basically, the problem is that gatsby doesn't know about the css, so fetches it dynamically at load time, by which time a giant chevron has already been rendered.
=> Allow css for svg fontawesome to be inlined to fix huge chevron flash

src/templates/extension-detail.js
Fixes #602 
This also fixes the link on the community tab:
=> Use correct json path for repository icon detection

site-validation/external-links.test.js
Now that we have #447, we do not need manual exemptions for dead links; they will not raise the build, they'll just be tracked as defects.
=> Remove dead link exemptions

.github/workflows/check-external-links.yml
Resolves #1096. I originally planned to mark the build red for new dead links, but there's no point, really, because a defect will be raised.
=> Do not mark build red if dead links were found

plugins/github-enricher/gatsby-node.js
I've fixed an issue which caused us to show a `/issues` github link for optaplanner and debezium, even though they didn't have github issues set up. Despite that, the dead link tracker keeps raising dead link issues (see, for example, #1123 and #1122). 
My best guess is that old bad data is sometimes popping up in the cache, especially since it's easier to cache the presence of something than the absence of something. To maybe fix this, I'm just going to start with a fresh cache.
=> Try new issues cache to try to resolve non-deterministic bug

plugins/github-enricher/gatsby-node.js
I noticed that https://quarkus.io/extensions/io.debezium/debezium-quarkus-outbox/ does not have a link to the quarkus-extension-metadata.yaml file. On investigation, it's because it's in a `resources-filtered` directory. I've updated to look there too. 
https://quarkus.io/extensions/io.quarkiverse.amazonservices/quarkus-amazon-lambda/ and https://quarkus.io/extensions/io.quarkiverse.googlecloudservices/quarkus-google-cloud-firestore/ use one-word folder names, so their extension metadata is also not found.
=> Also look in resources-filtered and one-word directories for extension metadata

src/components/headers/navigation.js
Training has been removed, and 'Guides' is now Documentation.
=> Update menus to match parent site

.github/workflows/build_and_publish.yml
Will hopefully reduce incidence of failures like https://github.com/quarkusio/extensions/actions/runs/10411458386, and at the very least will stop them blocking the deploy.
=> Reorder build to try to avoid hitting github api in consecutive steps

.github/workflows/check-external-links.yml
Dead link issues for Debezium and Optaplanner continue to baffle me. They're almost never reproducible, but once or twice I've reproduced them. The site generation fixed the issue some time ago (#1060), so I don't know why it's still popping up in some builds. I thought it was a caching issue, but I changed the cache name and that didn't help. 
This change switches dead link testing to run against a pre-built site, rather than doing a re-build, so at least what the link checker sees will be the same as what's on the live site. The downside is for ease it now runs after every scheduled build, so it runs more often. If that causes problems we can add an extra guard inside the run.
=> Use pre-built artifacts to reduce weird caching effects in dead link checking

.github/workflows/check-external-links.yml
The links test is currently silently failing. I don't know if the action will create the directory if it doesn't exist (and the docs don't say), but we will find out next run.
=> Download pre-built site to location where it would have been built

site-validation/bad-image-issue.java, site-validation/dead-link-issue.java
I'm hoping this will reduce incidences of the rate limiter killing the dead image check in the publish build.
=> Limit dead link issue query to the main repo

plugins/github-enricher/gatsby-node.js
It looks like #1128 broke yaml discovery for non-Camel paths:
```
warn Unsuccessful GitHub fetch for https://api.github.com/graphql - response is {"errors":[{"message":"Expected NAME, actual: (none) (\"\\n        \") at [66, 13]","locations":[{"line":66,"column":13}]}]}
warn Could not identify the extension yaml path for io.quarkiverse.freemarker:quarkus-freemarker; found  undefined
```
=> Fix graphql syntax for discovering yaml files

src/components/extension-card.js, src/components/extension-card.test.js
=> Mark cards for relocated extensions with text and different styling

src/templates/extension-detail.js
For various reasons, the image sizes need to be hardcoded in a few different places. Because of the hardcoding, they didn't match. We got away with that for normal images, but not for svgs.
Resolves #1186.
=> Make image size match image size

gatsby-node.js, src/components/util/guide-url-rewriter.js
Should sort out #1163, but let's wait and see what the CI says.
=> Do not show dead guides for superseded extensions

plugins/github-enricher/gatsby-node.js, src/maven/maven-info.js, src/maven/maven-info.test.js
I noticed we've had a bunch of builds failing lately because of 429s checking issue urls. That's caused by an error in https://github.com/quarkusio/extensions/pull/1223; instead of retrying on 429, it just fails on 429.
I also noticed the maven info has the same issue, which could explain why it's quite so brittle.
=> Correct usage of promise retry to actually retry

src/components/headers/navigation.js, src/components/headers/submenu.js, src/components/util/styles/breakpoints.js
This also fixes a few problems with the existing mobile support:
- There was unused code failing to add padding above the "Try this out CTA"
- Menu headings should be centred, not right-aligned
=> Cleaner mobile detection

src/components/extensions-list.js, src/components/filters/dropdown-filter.js, src/components/filters/filter-submenu.js, src/components/filters/filter-submenu.test.js, src/components/filters/filters.js, src/components/filters/filters.test.js, src/components/filters/search.js, src/components/filters/status-filter.js, src/components/filters/ticky-filter.js, src/components/filters/title.js, src/components/headers/submenu.js, src/components/headers/title-band.js, src/components/layout.js, src/components/sortings/sortings.js, src/components/util/styles/breakpoints.js, src/style.css
Before: 
After:
Light mode
Dark mode
The footer isn't right, and the styling for the sort needs to visually indicate that only one can be selected, but those can be done in follow-up PRs.
I also wonder if fonts need to be smaller across the board, but that can also be done as a follow-up. 
cc @insectengine
=> Mobile filter menus and extensions list page

src/templates/extension-detail.js
People sometimes struggle to find it. It's not as important as the guide, but it's more important than the coords, arguably.
=> Re-order metadata to make github more prominent

src/components/charts/contributions-chart.js, src/components/extensions-display/breadcrumb-bar.js, src/components/extensions-display/code-link.js, src/components/extensions-list.js, src/components/filters/filter-submenu.test.js, src/components/filters/filters.test.js, src/components/headers/navigation.test.js, src/components/headers/submenu.test.js, src/components/util/styles/breakpoints.js, src/style.css, src/templates/extension-detail.js
Fixes #392.
I've changed the layout to stack the columns on mobile, and also made the contributor graphs render nicely on mobile, and also on intermediate sizes.
After:
=> Make extension details page look good on mobile

plugins/github-enricher/gatsby-node.js, src/templates/extension-detail.js
For extensions with samples, we discover the samples correctly, but then what goes into graphql has the fields nulled out. This means nothing is displayed:
I was a bit confused how this could be happening, but it turns out to be a schema problem. It's an array type and I had a non-array type in the schema, and that caused the data to be blatted.
=> Fix problem with samples not displaying properly

.github/workflows/build_and_publish.yml
Better attempt to fix problem described in #1282. 
See discussion at https://github.com/puppeteer/puppeteer/issues/12818. I copied the fix from https://github.com/puppeteer/puppeteer/pull/13196; if it's good enough for puppeteer's own CI ...
=> Disable app armor to allow puppeteer on ubuntu 24

src/components/filters/compatibility-filter.test.js, src/components/filters/filters.test.js, src/components/filters/ticky-filter.js, src/components/filters/ticky-filter.test.js, src/components/util/pretty-category.js, src/components/util/pretty-category.test.js
"Ai" and "Openapi" and "Open Sdk" in the current menu look a bit silly. 
I've also added case-insensitive de-duplication, in case we get the same category with multiple casings.
=> Do not force lower-case categories which might be uppercase

.github/workflows/check-external-links.yml
Another victim of the ubuntu 24 upgrade. Link checking was failing, and because that step expects failures, it wasn't failing the build, it was just closing #1207 and #1094.
=> Disable app armor so links checking can run

gatsby-node.js, src/maven/maven-info.js
https://quarkus.io/extensions/extensions-added-december-2024/ shows optaplanner as being added in December, because the maven metadata is wrong, as a consequence of the move to Apache.  Since https://repo1.maven.org/maven2/org/optaplanner/optaplanner-quarkus-jackson/maven-metadata.xml disagrees with the listing https://repo1.maven.org/maven2/org/optaplanner/optaplanner-quarkus/, the tool is a bit stuck. It could try and parse directory listings, but it's simpler (if hackier) to pragmatically hardcode an earliest version for optaplanner.
=> Hardcode optaplanner version to work around maven metadata problem

src/components/extensions-list.js
#1298 introduced a new container element, but forgot to remove the padding and margins on the child elements.
=> Correct double margins

gatsby-node.js, gatsby-node.test.js, src/components/util/extension-slugger.js, src/components/util/extension-slugger.test.js
Old scheme: `/extensions-added-december-2024`
New scheme: `/new-extensions/december-2024`
I've also added a `new-extensions/` page which always shows the current month.
=> Change url for new extensions page to hierarchical structure

gatsby-node.js, gatsby-node.test.js, src/components/util/date-utils.js, src/components/util/extension-slugger.js, src/components/util/extension-slugger.test.js, src/maven/maven-info.js, src/templates/extensions-added-by-year-list.js, src/templates/extensions-added-by-year-list.test.js
Old scheme: 
http://quarkus.io/extensions/new-extensions/december-2024
http://quarkus.io/extensions/new-extensions/2024/december 
I've also made it so that http://quarkus.io/extensions/new-extensions/2024/ works
Some light refactoring is needed, but I wanted to get the new url live.
=> Make new-extensions urls hierarchical, add pages for each year

babel.config.js, jest.config.js, package-lock.json, package.json, plugins/github-enricher/gatsby-node.js, plugins/github-enricher/gatsby-node.test.js, plugins/github-enricher/github-helper.js, plugins/github-enricher/issue-count-helper.js, plugins/github-enricher/issue-count-helper.test.js, plugins/github-enricher/url-helper.js
Fixes #1326 
If a label cannot be found, use the extension name as a search query. (It has to be a search, not a filter, which increases the code complexity.)
=> Handle case when a quarkus core extension does not have a label

plugins/github-enricher/issue-count-helper.js
This stops `jgit` from being turned into a blank string in the issue url (see #1330).
=> Better regex to catch .git specifically

plugins/github-enricher/gatsby-node.js, plugins/github-enricher/labelExtractor.js
This should make the community tab show more tailored results, and activate the hyperlink to the quarkus-extension.yaml for the relocated smallrye-reactive extensions. 
I also spotted that we print a warning saying the yaml couldn't be found in the case where it's found, rather than the case where it isn't, so I've fixed that. 
Fixes #1327.
=> Special case paths for relocated smallrye-reactive

gatsby-node.js, test-integration/internal-links.test.js
Resolves #1864. 
We were limiting the number of extension nodes we created pages for to 1000, which worked great when there were fewer than 1000, but ... 
The dead link checker should have caught the issue but the regex for internal pages wasn't right, so it wasn't actually checking any pages.
=> Fix dead page links caused by limit on number of results in query

site-validation/dead-link-issue.java
Something is causing the dead link checker to fail to resolve most github issues (another rate limiter?). When this happens, it shouldn't spam the issue tracker with all the links.
=> Tame dead link checker

site-validation/dead-link-issue.java, site-validation/external-links.test.js
It's still spamming subscribers with dead link issues, despite the cap on how many issues it can raise at once.
=> Slow down links test

site-validation/external-links.test.js
I'm seeing a funny thing with the dead link checker where the actual test output has the correct dead links, but the file seems to have some spurious extra links. I assume it's a concurrency issue, but I'm puzzled.
=> Add diagnostic output for dead link checker
