quarkusio/extensions

- src/components/layout.js
- src/components/navigation.js
Partial resolution of #5.  
I've removed the lock on the page size, so it's got basic responsiveness. When resizing the page, the navbar behaved quite badly, so I've adjusted it to behave more like http://quarkus.io, with floating groups. 
I haven't done the work so handle very small page sizes, which needs a separate `@media` and hamburger menu.
> Do not lock page width

- jest-puppeteer.config.js
- package-lock.json
- package.json
- src/components/navigation.js
- src/components/navigation.test.js
Partial resolution of #5. I've added a dropdown menu, similar - but not yet identical - to what we use on http://quarkus.io. 
This makes navigation on mobile much better.
> Dropdown navigation menu on mobile

- .github/workflows/build_and_publish.yml
- .github/workflows/preview.yml
> Add workflow for surge preview

- gatsby-node.js
- gatsby-node.test.js
- src/style.css
- src/templates/extension-detail-page.test.js
- src/templates/extension-detail.js
Partial resolution of #76 ; we still have two cards, but now we cross-link the extension pages, and put a warning banner on the superseded one.
> Cross link extensions

- src/components/headers/navigation.js
This is needed to be consistent with main Quarkus site, so continuing work on #47.
> Add link to parent site on Quarkus logo

- gatsby-browser.js
- package-lock.json
- package.json
Dependabot did us a favour and reminded me of some fonts that came in on the starter that aren't being used anywhere.
> Remove unused fonts

- src/maven/maven-url.js
- src/maven/maven-url.test.js
This should improve the cache-friendliness.
Continuing work on #75.
> Check pom header rather than directory listing header

- plugins/github-enricher/gatsby-node.js
- plugins/github-enricher/gatsby-node.test.js
- src/templates/extension-detail.js
I've included (where we can) a link to their actual yaml file, as well as the generic documentation links for this area.
> Add guidance for extension owners on how to update their information

- src/components/extension-card.js
> Fix incorrect guard, a copy paste error

- src/components/extensions-display/installation-instructions.js
- src/components/extensions-display/installation-instructions.test.js
not perfect; but *only* having Maven I find sad when we have quarkus cli and ~30% uses gradle.
Fixes #17
> add quarkus cli/gradle cmds. Fixes #17

- src/components/extension-card.js
> Add a little bit extra to the height of card divs so we do not cut off low letters

- src/templates/extension-detail-page.test.js
- src/templates/extension-detail.js
> Add "built with" information to details page

- gatsby-node.js
- src/templates/extension-detail-page.test.js
- src/templates/extension-detail.js
> Show minimum Java version on details page

- .github/workflows/preview-teardown.yml
- .github/workflows/preview.yml
- Also changed the URL to avoid Chrome warnings about phishing
> Teardown preview URLs

- src/templates/extension-detail-page.test.js
- src/templates/extension-detail.js
> Make issues text a hyperlink

- plugins/github-enricher/gatsby-node.js
Now that we have scm information for the quarkus core extensions, we're seeing builds failing on github queries. Longer term we may want to batch the github access, but in the short term, let's put in some retries.
> Retry access to github API

- src/components/extensions-display/extension-metadata.js
- src/components/layout.js
- src/templates/extension-detail-page.test.js
- src/templates/extension-detail.js
> Rename headers and remove repeated version string

- test-integration/links.test.js
These should now be unneeded, following https://github.com/quarkusio/quarkus-extension-catalog/pull/52
> Remove resolved exceptions

- src/templates/extension-detail.js
- src/templates/extension-detail.test.js
See discussion here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Issues.20for.20quarkus.2Eio.2Fextensions/near/351526545
> Feature request: add group id and artifact id into metadata table

- test-integration/links.test.js
See https://github.com/quarkiverse/quarkus-asyncapi/pull/71
> Remove exemptions for dead links which are fixed, add new exemption

- plugins/github-enricher/gatsby-node.js
The caching logic has several problems, so I’m not totally sure why the live site is showing good information. I did notice builds were slow, but had thought it was maybe a GitHub infrastructure issue. In fact, I think it was failed retries.
- Syntax error in the graphQL queries for the ‘cache exists’ paths
- Excessiuvely long backoffs, which allow the build to cope with rate limits, but just slow things down when using caching
- Destructuring objects which don’t have all fields (because we didn’t ask for them)
- Overwriting cached data with undefined
I switched from caching the constructed scmInfo object to caching the raw responses from the GitHub API. That seems to make it easier to avoid some concurrency-related issues and reduces the code complexity.
> Correct query and caching logic

- .github/workflows/build_and_publish.yml
- .github/workflows/preview.yml
#322 got the builds working, but with the wrong branch, so the new content is not live.
> Fix deploy branch

- .github/workflows/build_and_publish.yml
Actions is behaving strangely; not attempting to build some changes, including PRs, and failing against stale code on other builds. My best guess is that I think I might have created a problem with a rebase or a force push.
> Trivial change

- .github/workflows/build_and_publish.yml
.... and also fix the path prefixes.
> Reinstate integration tests

- .github/workflows/build_and_publish.yml
What a headache. The tests are only failing on main, not on the preview, and they're blocking a fix.
> Remove - again - integration tests, which are failing on 'main' 

- .github/workflows/build_and_publish.yml
- gatsby-config.js
See discussion in https://github.com/quarkusio/extensions/pull/333. I think the issue may be segment, so removing it for the moment.
> Disable segment and reinstate integration tests to resolve build issue

- .github/workflows/build_and_publish.yml
> Reinstate separate 'deploy' job for deploys

- plugins/github-enricher/gatsby-node.test.js
I inadvertently committed disabled tests as part of #352. (I'd filtered to one test to debug, and then forgotten I'd done done that.) The tests needed some updates for the new structure, so this PR does that.
> Update tests, following refactoring

- gatsby-config.js
- src/components/headers/navigation.js
[See parent site #1790 ](https://github.com/quarkusio/quarkusio.github.io/pull/1790/).
> Add Portuguese to internationalisation menu

- src/components/headers/navigation.js
See https://github.com/quarkusio/quarkusio.github.io/pull/1779
> Update menu title

- plugins/github-enricher/sponsorFinder.js
Reverses #376. Annoyingly, I can't think of an easy way to flush caches without two code changes. An environment build would do it, but only a few people have access to set them, and it still needs setting and unsetting.
> Undo the emptying of the cache

- src/components/headers/navigation.js
- Follow up to https://github.com/quarkusio/quarkusio.github.io/pull/1810
> Add Brasileiro to the Portuguese menu items

- jest-setup.js
- package-lock.json
- package.json
- plugins/github-enricher/gatsby-node.js
- plugins/github-enricher/sponsorFinder.js
- plugins/github-enricher/sponsorFinder.test.js
- src/components/charts/contributions-chart.js
- src/components/charts/contributions-chart.test.js
- src/components/filters/dropdown-filter.js
- src/components/util/styles/style.js
- src/components/util/styles/style.test.js
- src/style.js
- src/templates/extension-detail.js
- src/templates/extension-detail.test.js
Partial resolution of #297.
I've started with showing the individuals, since that won't need an opt-in.
> Show individual contributors in a pie chart

- src/components/charts/contributions-chart.js
> Add minimum spacing in contributor chart

- src/style.css
These changes are to keep the extensions section consistent with the main site when PR1817 is merged.
> change breakpoint and update page margin

- plugins/github-enricher/gatsby-node.js
- plugins/github-enricher/gatsby-node.test.js
- plugins/github-enricher/sponsorFinder.js
- plugins/github-enricher/sponsorFinder.test.js
- src/components/charts/contributions-chart.js
- src/components/util/styles/style.js
- src/components/util/styles/style.test.js
- src/templates/extension-detail.js
> Show company commit statistics

- plugins/github-enricher/gatsby-node.js
- src/components/charts/contributions-chart.js
- src/components/util/styles/style.js
- src/components/util/styles/style.test.js
- src/style.css
- src/templates/extension-detail.js
I also fixed an issue with the palette generation.
Before:
After:
> Re-arrange company to be a ring in the main contributor doughnut charts

- util/dead-link-issue.java
> Try installation token method

- .github/workflows/build_and_publish.yml
The eslint step is being skipped, and I think it's because of a guard that I copied from the docs, but which doesn't make sense.
> Eslint not executing in build

- plugins/github-enricher/sponsorFinder.js
- plugins/github-enricher/sponsorFinder.test.js
Resolves https://github.com/quarkusio/extensions/issues/443 (to the extent that the extensions front-end can).
> Better company name normalisation

- gatsby-config.js
> Suppress warnings about how sharp cannot transform svgs 

- gatsby-node.js
Tactical resolution for #616. We should do more than print a warning, we should raise a defect; but I will do the quick fix first to unstick the build.
> Tolerate dead image links

- plugins/github-enricher/gatsby-node.js
- plugins/github-enricher/gatsby-node.test.js
Resolves #630 (or will, once things work through the cache).
> Tolerate scm urls with trailing .git

- plugins/github-enricher/gatsby-node.js
- plugins/github-enricher/gatsby-node.test.js
Resolves #632 (although it may take a little while for the data to work through the caches).
> Tolerate Apache gitbox urls

- src/templates/extension-detail.js
> Add link in top warning bar for superceded extensions

- gatsby-node.js
- gatsby-node.test.js
- package-lock.json
- package.json
- plugins/github-enricher/sponsorFinder.realdata.test.js
- src/components/extensions-list.test.js
- src/components/util/extension-slugger.js
- src/maven/maven-info.js
- src/maven/maven-info.test.js
- src/maven/pom-reader.js
- src/maven/pom-reader.test.js
- src/templates/extension-detail.js
- src/templates/extension-detail.test.js
… instead of assuming extensions with the same artifact id have a relationship. This resolves #210.
> Leverage maven relocation information

- .github/workflows/build_and_publish.yml
- .gitignore
- gatsby-node.js
- package-lock.json
- package.json
- site-validation/bad-image-issue.java
- src/data/image-validation.js
- src/data/image-validation.test.js
> Better image validation, raise defects for invalid images

- src/components/util/guide-url-rewriter.js
See https://github.com/apache/camel-quarkus/issues/5814#issuecomment-1968999263
Should resolve https://github.com/quarkusio/extensions/issues/671 and others.
> Drop dead links if they're camel ones

- gatsby-config.js
- gatsby-node.js
- package-lock.json
- package.json
Resolves #613, and also shrinks the site archive size slightly (I think because the images are no longer base64 encoded).
> Use a plugin to force file-loader for fonts

- site-validation/external-links.test.js
Resolves #854.
It looks like the jitter and retry count are only honoured for 500s, not 429. It also looks like linkinator will not retry if there's no `retry-after` header. I wonder if that's what's changed? 
If that is the issue, we can try  manually retrying. 
I also had set the jitter far too small, since the default is 3000.
> Slow test down more and manually retry to try and resolve 429s

- babel.config.js
- jest.config.js
- jest.integration.config.js
- package-lock.json
- package.json
- src/components/util/guide-url-rewriter.js
- src/components/util/guide-url-rewriter.test.js
- src/maven/maven-url.js
- src/maven/maven-url.test.js
Like https://github.com/quarkusio/extensions/pull/195 from dependabot, but actually works.
> Upgrade url-exist and patch up test and jest config

- gatsby-node.js
- plugins/download-data/gatsby-node.js
- plugins/download-data/tableau-fetcher.js
- plugins/download-data/tableau-fetcher.test.js
> Include group id in unique identifier for download data

- plugins/github-enricher/gatsby-node.js
- plugins/github-enricher/gatsby-node.test.js
I've done two things: 
- validate issue urls, but only if we don't have an issue count to avoid false-negatives caused by 429s
- remove double slashes in urls
This should sort out #986 and #972, but the fix may not show until the cache is refreshed. I'll let the dead link CI close them.
> Tidy some dead issue links

- src/components/extensions-list.test.js
- src/components/filters/category-filter.js
- src/components/filters/category-filter.test.js
- src/components/filters/compatibility-filter.test.js
- src/components/filters/dropdown-filter.js
- src/components/filters/dropdown-filter.test.js
- src/components/filters/filters.js
- src/components/filters/filters.test.js
- src/components/filters/keyword-filter.js
- src/components/filters/keyword-filter.test.js
- src/components/filters/search.js
- src/components/filters/status-filter.test.js
- src/components/filters/version-filter.test.js
> Read and set query strings for all filters

- src/style.css
When it's reinstated, it should have a toggle, to align with the parent site. See https://github.com/quarkusio/quarkusio.github.io/pull/1951.
> Disable dark mode

- src/components/extensions-list.js
> Switch from auto to fr unit to enforce size being the same

- src/components/extensions-list.js
- src/components/sortings/sortings.js
> Update download data wording

- __mocks__/match-media.js
- src/components/headers/dark-mode-toggle.js
- src/components/headers/dark-mode-toggle.test.js
- src/components/headers/navigation.js
- src/components/headers/navigation.test.js
- src/components/seo.js
- src/components/util/dark-mode-helper.js
- src/pages/404.js
- src/pages/index.js
- src/style.css
- src/templates/extension-detail.js
Mirror of https://github.com/quarkusio/quarkusio.github.io/pull/1962
> Add toggle for dark mode, using local storage

- .github/workflows/preview.yml
See https://github.com/quarkusio/extensions/pull/1031 and #1020.
> Do not trigger previews on mainline builds

- .github/workflows/preview.yml
> Another attempt: Do not trigger previews on mainline builds

- .github/workflows/preview.yml
> Diagnostics: Notionally include all branches in filter

- .github/workflows/preview.yml
See #1033. I'm seeing such inconsistent behaviour, I think I should try with a 'new' pull request, rather than pushes on existing ones.
> Despair: Go back to the syntax that should work

- site-validation/bad-image-issue.java
- site-validation/dead-link-issue.java
Resolves #789. (Hopefully, although as it's an intermittent issue, it will take a while to confirm.)
> Update github-api to pick up secondary rate limit improvements

- src/components/extensions-list.test.js
- src/components/filters/filters.js
- src/components/filters/filters.test.js
- src/pages/index.js
> Include artifact id in what gets searched

- src/maven/maven-info.js
> Do not modify shared objects in async code

- site-validation/bad-image-issue.java
- site-validation/dead-link-issue.java
I doubt this will help with #789, but worth checking.
> Bump GitHub Api to latest version

- site-validation/bad-image-issue.java
- site-validation/dead-link-issue.java
> Use forked GitHub API to properly handle 429s

- site-validation/bad-image-issue.java
- site-validation/dead-link-issue.java
The previous hash didn't actually build properly with Jitpack
> Bump version of forked GitHub api

- plugins/github-enricher/gatsby-node.js
Extensions such as [pinecone](https://quarkus.io/extensions/org.apache.camel.quarkus/camel-quarkus-pinecone/) live in https://github.com/apache/camel-quarkus/tree/main/extensions, which wasn't included in the search rules.
> Add new extension yaml finding rule for some camel extensions

- plugins/github-enricher/gatsby-node.js
We are publishing dead issue links for optaplanner and debezium. The root cause is that if we've hit GitHub hard elsewhere in the build, when we try and follow the issues link, we get a 429, and conclude it's ok to publish. Adding a retry should sort this out.
```
2024-11-06T22:33:36.5001423Z Bypassing issue url cache for optaplanner
2024-11-06T22:33:36.5002763Z Bypassing issue url cache for optaplanner
2024-11-06T22:33:40.2824309Z Validating issue url for https://github.com/kiegroup/optaplanner/issues because issues is 0
2024-11-06T22:33:42.4882007Z URL chain for https://github.com/kiegroup/optaplanner/issues is [
2024-11-06T22:33:42.4882913Z   {
2024-11-06T22:33:42.4883805Z     url: 'https://github.com/kiegroup/optaplanner/issues',
2024-11-06T22:33:42.4884527Z     redirect: false, …
```
> Retry on 429 to avoid false positives on dead links

- src/components/footer.js
> Improve appearance of footer on mobile

- src/components/extensions-display/tabs.js
- src/style.css
- src/templates/extension-detail.js
Current state: 
New design from @insectengine :
New implementation:
> Improve look of tabs

- plugins/github-enricher/gatsby-node.js
Follow on from #1223, since that seems to have (finally!) solved the dead link problem.
> Tidy logging now that problem is confirmed fixed

- src/components/headers/navigation.js
Companion to https://github.com/quarkusio/quarkusio.github.io/pull/2190
> Update `continuum` url to match parent site

- src/components/filters/filters.js
- src/components/filters/filters.test.js
> Do case-insensitive comparison of keyword and category strings

- __mocks__/test-data/maven-metadata.xml
- gatsby-node.js
- package-lock.json
- package.json
- src/components/sortings/sortings.js
- src/components/sortings/sortings.test.js
- src/components/sortings/timestamp-extension-comparator.js
- src/maven/maven-info.js
- src/maven/maven-info.test.js
- src/pages/index.js
- src/templates/extension-detail.js
I've also added a 'first released' field on the detail page.
Resolves #1273.
> Add 'most recently added' sort option

- src/templates/extension-detail.js
- src/templates/extensions-added-list.js
> Sort new extensions before they hit the page to avoid flash on load

- src/pages/404.js
> Adjust 404 page for production domain

- site-validation/dead-link-issue.java
There's a lot to be said for IDE support. :)
> Correct checked exception

- site-validation/external-links.test.js
Retrying is (a) having promise problems and (b) massively slowing down the build.
> Do not raise dead link exceptions for 429s

- site-validation/external-links.test.js
Intended to solve 
```
Attempted to log "Giving a pass because of too many tries to {
url: 'https://github.com/apache/camel-quarkus-examples/blob/main/fhir',
status: 429,
state: 'BROKEN',
parent: 'http://localhost:9000/extensions/org.apache.camel.quarkus/camel-quarkus-fhir/',
failureDetails: [
{
config: [Object],
data: [PassThrough],
headers: [Object],
status: 429,
statusText: 'Too Many Requests',
request: [Object]
}
]
}".
```
> Wait for async events in dead link checker

- .idea/codeStyles/Project.xml
- .idea/copyright/profiles_settings.xml
Looks like we have .idea files committed, but they're not complete, since I got some formatting churn when moving to a new machine. Since we have the files, they may as well be sufficient to avoid formatting churn.
> Share ide formatting settings

- src/components/headers/navigation.js
Reflecting https://github.com/quarkusio/quarkusio.github.io/pull/2355
While I was there I noticed the menu order had got out of sync, so I've fixed that too.
> Add new menu option for Spring splash page

- site-validation/bad-image-issue.java
- site-validation/dead-link-issue.java
Fixes build failures in raise-defects step:
```
Error:  [ERROR] No suitable JDK was found for requested version: 17
```
> Update Java version used by JBang

- plugins/github-enricher/sponsorFinder.js
- plugins/github-enricher/sponsorFinder.test.js
- src/templates/extension-detail.js
- test-integration/detail-page.test.js
> Normalise to compound entity for IBM and Red Hat
